Algoritmo "Entrada e Saida de Dados"

// Descrição   : Entrada e Saida de Dados
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/09/2020
Var
// Seção de Declarações das variáveis 
   nome: caractere
   nota: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite seu nome:")
   leia(nome)
   escreval("Digite a sua idade:")
   leia(nota)
   
   escreval("o nome digitado foi: ", nome)
   escreval("a idade digitada foi: ", nota)

Fimalgoritmo